/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * WelcomeFrame.java
 *
 * Created on Feb 15, 2010, 6:01:37 PM
 */

package org.cit.CloudComputing;

import javax.swing.*;

/**
 *
 * @author JAGANATHAN-N
 */
public class WelcomeFrame extends javax.swing.JFrame {

    static Software[] list_of_softwares;
    public static WelcomeFrame instance=null;
    /** Creates new form WelcomeFrame */
    public WelcomeFrame() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblInfo = new javax.swing.JLabel();
        cmbList = new javax.swing.JComboBox();
        btnGo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Go Cloud - Welcome");
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setName("frmConnect"); // NOI18N

        lblInfo.setText("Select a software");

        btnGo.setText("Connect");
        btnGo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(159, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addComponent(cmbList, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(169, Short.MAX_VALUE)
                .addComponent(btnGo)
                .addGap(153, 153, 153))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblInfo)
                .addGap(18, 18, 18)
                .addComponent(cmbList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(btnGo)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoActionPerformed
        // TODO add your handling code here:
        try{
        int matched_index=-1;
        for(int i=0;i<list_of_softwares.length;i++){
            if(list_of_softwares[i].name.equalsIgnoreCase(cmbList.getSelectedItem().toString())){
                matched_index=i;
                break;
            }
        }
        if (list_of_softwares[matched_index].type.equalsIgnoreCase("JAR")){
            System.out.println(list_of_softwares[matched_index].server_ip);
            System.out.println(list_of_softwares[matched_index].server_port);
            CloudClient.server_ip=list_of_softwares[matched_index].server_ip;
            CloudClient.server_port=Integer.parseInt(list_of_softwares[matched_index].server_port);
            
            if (list_of_softwares[matched_index].name.equalsIgnoreCase("TextEditor")){
                    ClientBrowser.main(new String[]{});
            }else{
                    System.out.println("\n\n\n" +list_of_softwares[matched_index].name);
            }
            this.setVisible(false);
        }else{
            //Handle Windows here
        }
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnGoActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]){
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                instance=new WelcomeFrame();
                if (ClientBrowser.isLicenseOK()){
                     instance.setVisible(true);
                     for(Software s:list_of_softwares){
                         instance.cmbList.addItem(s.name);
                     }
                }else{
                     JOptionPane.showMessageDialog(new JPanel(), "You need a license to use this software !");
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGo;
    private javax.swing.JComboBox cmbList;
    private javax.swing.JLabel lblInfo;
    // End of variables declaration//GEN-END:variables

}
